model_version: 4.1.0 (Correction Model, Imputation Fixed)
description: XGBoost regressor predicting the DELTA (Expt - DFT) band gap correction.
target: delta_gap (Expt - PBE)
cv_scheme: REQUIRES GroupKFold (composition-held-out) validation on 'groups_all'
best_cv_rmse_eV: TBD (run GroupKFold validation)
hyperparameters:
  n_estimators: 806
  learning_rate: 0.02024
  max_depth: 5
  min_child_weight: 2.18
  subsample: 0.968
  colsample_bytree: 0.74
  gamma: 0.0022
  reg_alpha: 1.5
  reg_lambda: 7.0
  objective: reg:squarederror
  eval_metric: rmse
  n_jobs: -1
  random_state: 42
  verbosity: 0
training_samples: 2381
feature_names:
- gap pbe
- Ag
- Al
- As
- Au
- B
- Ba
- Be
- Bi
- Br
- C
- Ca
- Cd
- Ce
- Cl
- Co
- Cr
- Cs
- Cu
- Dy
- Er
- Eu
- F
- Fe
- Ga
- Gd
- Ge
- H
- Hf
- Hg
- Ho
- I
- In
- Ir
- K
- La
- Li
- Lu
- Mg
- Mn
- Mo
- N
- Na
- Nb
- Nd
- Ni
- O
- Os
- P
- Pb
- Pd
- Pr
- Pt
- Rb
- Re
- Rh
- Ru
- S
- Sb
- Sc
- Se
- Si
- Sm
- Sn
- Sr
- Ta
- Tb
- Tc
- Te
- Th
- Ti
- Tl
- Tm
- U
- V
- W
- Xe
- Y
- Yb
- Zn
- Zr
- MagpieData minimum Number
- MagpieData maximum Number
- MagpieData range Number
- MagpieData mean Number
- MagpieData avg_dev Number
- MagpieData mode Number
- MagpieData minimum MendeleevNumber
- MagpieData maximum MendeleevNumber
- MagpieData range MendeleevNumber
- MagpieData mean MendeleevNumber
- MagpieData avg_dev MendeleevNumber
- MagpieData mode MendeleevNumber
- MagpieData minimum AtomicWeight
- MagpieData maximum AtomicWeight
- MagpieData range AtomicWeight
- MagpieData mean AtomicWeight
- MagpieData avg_dev AtomicWeight
- MagpieData mode AtomicWeight
- MagpieData minimum MeltingT
- MagpieData maximum MeltingT
- MagpieData range MeltingT
- MagpieData mean MeltingT
- MagpieData avg_dev MeltingT
- MagpieData mode MeltingT
- MagpieData minimum Column
- MagpieData maximum Column
- MagpieData range Column
- MagpieData mean Column
- MagpieData avg_dev Column
- MagpieData mode Column
- MagpieData minimum Row
- MagpieData maximum Row
- MagpieData range Row
- MagpieData mean Row
- MagpieData avg_dev Row
- MagpieData mode Row
- MagpieData minimum CovalentRadius
- MagpieData maximum CovalentRadius
- MagpieData range CovalentRadius
- MagpieData mean CovalentRadius
- MagpieData avg_dev CovalentRadius
- MagpieData mode CovalentRadius
- MagpieData minimum Electronegativity
- MagpieData maximum Electronegativity
- MagpieData range Electronegativity
- MagpieData mean Electronegativity
- MagpieData avg_dev Electronegativity
- MagpieData mode Electronegativity
- MagpieData minimum NsValence
- MagpieData maximum NsValence
- MagpieData range NsValence
- MagpieData mean NsValence
- MagpieData avg_dev NsValence
- MagpieData mode NsValence
- MagpieData minimum NpValence
- MagpieData maximum NpValence
- MagpieData range NpValence
- MagpieData mean NpValence
- MagpieData avg_dev NpValence
- MagpieData mode NpValence
- MagpieData minimum NdValence
- MagpieData maximum NdValence
- MagpieData range NdValence
- MagpieData mean NdValence
- MagpieData avg_dev NdValence
- MagpieData mode NdValence
- MagpieData minimum NfValence
- MagpieData maximum NfValence
- MagpieData range NfValence
- MagpieData mean NfValence
- MagpieData avg_dev NfValence
- MagpieData mode NfValence
- MagpieData minimum NValence
- MagpieData maximum NValence
- MagpieData range NValence
- MagpieData mean NValence
- MagpieData avg_dev NValence
- MagpieData mode NValence
- MagpieData minimum NsUnfilled
- MagpieData maximum NsUnfilled
- MagpieData range NsUnfilled
- MagpieData mean NsUnfilled
- MagpieData avg_dev NsUnfilled
- MagpieData mode NsUnfilled
- MagpieData minimum NpUnfilled
- MagpieData maximum NpUnfilled
- MagpieData range NpUnfilled
- MagpieData mean NpUnfilled
- MagpieData avg_dev NpUnfilled
- MagpieData mode NpUnfilled
- MagpieData minimum NdUnfilled
- MagpieData maximum NdUnfilled
- MagpieData range NdUnfilled
- MagpieData mean NdUnfilled
- MagpieData avg_dev NdUnfilled
- MagpieData mode NdUnfilled
- MagpieData minimum NfUnfilled
- MagpieData maximum NfUnfilled
- MagpieData range NfUnfilled
- MagpieData mean NfUnfilled
- MagpieData avg_dev NfUnfilled
- MagpieData mode NfUnfilled
- MagpieData minimum NUnfilled
- MagpieData maximum NUnfilled
- MagpieData range NUnfilled
- MagpieData mean NUnfilled
- MagpieData avg_dev NUnfilled
- MagpieData mode NUnfilled
- MagpieData minimum GSvolume_pa
- MagpieData maximum GSvolume_pa
- MagpieData range GSvolume_pa
- MagpieData mean GSvolume_pa
- MagpieData avg_dev GSvolume_pa
- MagpieData mode GSvolume_pa
- MagpieData minimum GSbandgap
- MagpieData maximum GSbandgap
- MagpieData range GSbandgap
- MagpieData mean GSbandgap
- MagpieData avg_dev GSbandgap
- MagpieData mode GSbandgap
- MagpieData minimum GSmagmom
- MagpieData maximum GSmagmom
- MagpieData range GSmagmom
- MagpieData mean GSmagmom
- MagpieData avg_dev GSmagmom
- MagpieData mode GSmagmom
- MagpieData minimum SpaceGroupNumber
- MagpieData maximum SpaceGroupNumber
- MagpieData range SpaceGroupNumber
- MagpieData mean SpaceGroupNumber
- MagpieData avg_dev SpaceGroupNumber
- MagpieData mode SpaceGroupNumber
feature_count: 213
